#!/usr/bin/env python

import time
import zmqsub
import sys

if __name__ == '__main__' :
	try :
		url = sys.argv[1]
	except IndexError :
		url = 'tcp://*:4501'

	zs = zmqsub.JSONZMQSub(url)
	try :
		while True :
			try :
				print '%s %s' % (time.ctime(), zs.recv())
			except zmqsub.NoMessagesException :
				time.sleep(0.05)
	except KeyboardInterrupt :
		pass
